### ISSUE TITLE
Unknown error while finetuning   

### ISSUE THREAD

**Issue by roshan2024nar** [huggingface/instruction-tuned-sd#18]
Hello,
I have uploaded my dataset on hub and its looks as required
but when i start the training im getting error which im unable to resolve 
below is cmd which im running on colab as well as on my local jupyter since i have windows 
 
 ERROR:
 [C:\Users\itsun\anaconda3\Lib\site-packages\transformers\utils\generic.py:260](file:///C:/Users/itsun/anaconda3/Lib/site-packages/transformers/utils/generic.py:260): UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[C:\Users\itsun\anaconda3\Lib\site-packages\transformers\utils\generic.py:260](file:///C:/Users/itsun/anaconda3/Lib/site-packages/transformers/utils/generic.py:260): UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[C:\Users\itsun\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60](file:///C:/Users/itsun/anaconda3/Lib/site-packages/pandas/core/arrays/masked.py:60): UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
[C:\Users\itsun\anaconda3\Lib\site-packages\diffusers\utils\outputs.py:63](file:///C:/Users/itsun/anaconda3/Lib/site-packages/diffusers/utils/outputs.py:63): UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[C:\Users\itsun\anaconda3\Lib\site-packages\transformers\utils\generic.py:260](file:///C:/Users/itsun/anaconda3/Lib/site-packages/transformers/utils/generic.py:260): UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.0+cu121 with CUDA 1201 (you have 2.2.0+cu118)
    Python  3.11.7 (you have 3.11.5)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
[C:\Users\itsun\anaconda3\Lib\site-packages\diffusers\utils\outputs.py:63](file:///C:/Users/itsun/anaconda3/Lib/site-packages/diffusers/utils/outputs.py:63): UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
2024-02-13 13:30:59.088469: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From [C:\Users\itsun\anaconda3\Lib\site-packages\keras\src\losses.py:2976](file:///C:/Users/itsun/anaconda3/Lib/site-packages/keras/src/losses.py:2976): The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

[C:\Users\itsun\anaconda3\Lib\site-packages\accelerate\accelerator.py:394](file:///C:/Users/itsun/anaconda3/Lib/site-packages/accelerate/accelerator.py:394): UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Traceback (most recent call last):
  File "f:\roshan\image2paint\instruction-tuned-sd\finetune_instruct_pix2pix.py", line 1138, in <module>
    main()
  File "f:\roshan\image2paint\instruction-tuned-sd\finetune_instruct_pix2pix.py", line 473, in main
    raise ImportError(
ImportError: Make sure to install wandb if you want to use it for logging during training.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\itsun\anaconda3\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\itsun\anaconda3\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\itsun\anaconda3\Lib\site-packages\accelerate\commands\launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "C:\Users\itsun\anaconda3\Lib\site-packages\accelerate\commands\launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\itsun\\anaconda3\\python.exe', 'finetune_instruct_pix2pix.py', '--pretrained_model_name_or_path=timbrooks/instruct-pix2pix', '--dataset_name=jinwoos/cartoonizer-dataset', '--use_ema', '--enable_xformers_memory_efficient_attention', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=4', '--gradient_checkpointing', '--max_train_steps=15000', '--checkpointing_steps=5000', '--checkpoints_total_limit=1', '--learning_rate=5e-05', '--lr_warmup_steps=0', '--mixed_precision=fp16', '--val_image_url=https://hf.co/datasets/diffusers/diffusers-images-docs/resolve/main/mountain.png', '--validation_prompt=Generate a cartoonized version of the natural image', '--seed=42', '--output_dir=cartoonization-finetuned', '--report_to=wandb', '--push_to_hub']' returned non-zero exit status 1.

sorry for pasting whole error, thank you for the help

**Comment by sayakpaul** [comment]
```
ImportError: Make sure to install wandb if you want to use it for logging during training.
```
