### ISSUE TITLE
convert for automatic1111

### ISSUE THREAD

**Issue by kigy1** [huggingface/instruction-tuned-sd#23]
hello, thank you for your great work.

I wonder how (convert model) make it work in automatic1111 (img2img) 

I try this code https://gist.github.com/jachiam/8a5c0b607e38fcc585168b90c686eb05 but its not work with FileNotFoundError: [Errno 2] No such file or directory: 'E:\\pix2pix mod\\v4d25\\checkpoint-15000\\unet\\diffusion_pytorch_model.bin'

any way to make it like this file https://huggingface.co/timbrooks/instruct-pix2pix/blob/main/instruct-pix2pix-00-22000.safetensors

thanks again...

**Comment by sayakpaul** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'E:\pix2pix mod\v4d25\checkpoint-15000\unet\diffusion_pytorch_model.bin'

Maybe provide the correct path?

**Comment by kigy1** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: 'E:\pix2pix mod\v4d25\checkpoint-15000\unet\diffusion_pytorch_model.bin'
> 
> Maybe provide the correct path?

it show me it need diffusion_pytorch_model.bin  so I rename diffusion_pytorch_model.safetensors to .bin 
then this what happened

Traceback (most recent call last):
  File "C:\Users\GAMER\Desktop\New folder (6)\convert_diffusers_to_sd.py", line 216, in <module>
    unet_state_dict = torch.load(unet_path, map_location='cpu')
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\pix2pix mod\\v4d25\\unet\\diffusion_pytorch_model.bin'

C:\Users\GAMER\Desktop\New folder (6)>python convert_diffusers_to_sd.py --model_path "E:\pix2pix mod\v4d25" --checkpoint_path "C:\Users\GAMER\Desktop\New folder (6)\result\new.ckpt"
Traceback (most recent call last):
  File "C:\Users\GAMER\Desktop\New folder (6)\convert_diffusers_to_sd.py", line 216, in <module>
    unet_state_dict = torch.load(unet_path, map_location='cpu')
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xe0'.

I'm not sure if this the correct way to convert it

**Comment by sayakpaul** [comment]
You cannot just be renaming a pickle file to have the safetensors extension. I would suggest making appropriate modifications to the conversion script for your needs. 

Since this is not an issue directly to this repository, I am going to close this.
