### ISSUE TITLE
Incorrect DATASET_ID and OUTPUT_DIR for Low-level Image Processing, Fine-tuning from InstructPix2Pix Example?

### ISSUE THREAD

**Issue by Akari-T** [huggingface/instruction-tuned-sd#7]
Hello! Thank you for an amazing blog - I have been trying to figure out how to fine tune InstructPix2Pix and it gave me a lot of insight!

In the README, the DATASET_ID and OUTPUT_DIR for the low-level image processing example for fine-tuning InstructPix2Pix had paths to the cartoonization dataset. Should it be 
  export DATASET_ID="instruction-tuning-sd/low-level-image-proc"
  export OUTPUT_DIR="low-level-img-proc-scratch"
instead?

Sorry for a minor question!

**Comment by sayakpaul** [comment]
That is right :) 

Feel free to send over a PR.

**Comment by XJHH108** [comment]
Have you ever encountered this error？
Traceback (most recent call last):
  File "E:\Image_Transfer\instruction_tuning_cartoonizer\instruction-tuned-sd\finetune_instruct_pix2pix.py", line 1137, in <module>
    main()
  File "E:\Image_Transfer\instruction_tuning_cartoonizer\instruction-tuned-sd\finetune_instruct_pix2pix.py", line 506, in main
    create_repo(repo_name, exist_ok=True, token=args.hub_token)
  File "E:\anaconda\envs\pytorch\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "E:\anaconda\envs\pytorch\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'hj566/$OUTPUT_DIR'.
